export const meta = {
  name: 'autonomous-eng-os',
  description: "Build a CONCRETE, ENFORCEABLE operating system that changes how Claude Code works on this product PERMANENTLY, so the founder (non-technical) never re-lives today's failure: (1) treat his input as rough INTENT and auto-build the COMPLETE production-grade thing incl. every nano-detail he won't ask for, (2) NEVER execute his/anyone's guessed solution blindly - prove root cause empirically first, (3) NEVER claim done until proven on the real flow, (4) operate as a full multi-domain org structurally. Grounds in TODAY's real incident, audits the existing autonomy docs (which FAILED to prevent it), researches elite practices, and SHIPS enforceable artifacts (binding protocol + production-readiness checklist + reusable production-build workflow + hooks + CLAUDE.md binding + red-team). ANTI-BLOAT: sharp + enforceable, not a generic shelf doc.",
  phases: [
    { title: 'DiagnoseResearch', detail: 'today post-mortem + audit existing OS + research elite practices/prod-checklist/non-tech-founder/enforcement' },
    { title: 'Design', detail: 'synthesize the sharp enforceable operating system grounded in today failures' },
    { title: 'Build', detail: 'WRITE artifacts: binding protocol + readiness checklist + reusable workflow + hooks + CLAUDE.md/memory binding' },
    { title: 'RedTeam', detail: 'replay today incident through the new system; prove it prevents each failure; close gaps' },
  ],
}
const CTX = "CONTEXT - TODAY (2026-06-21) was a black day: I spent an ENTIRE day + millions of tokens failing to fix a SIMPLE voice bug (a bloated cross-vertical prompt made the small Groq model loop). The non-technical founder is exhausted + harmed. THE NAMED FAILURES (fix these structurally): (1) I built exactly his literal words + nothing more - missed the production nano-details a real team builds automatically (his example: an app crashed/was slow because I added NO pagination / NO lazy-loading - he never asked, but a team would). (2) I EXECUTED his beginner debugging guesses (it is the penalty, reset max to 90) instead of proving the real cause - a mad person advising a genius, and the genius obeyed. (3) I said done repeatedly when it was not - sent him to test unverified builds over and over. (4) I thrashed (whack-a-mole) instead of one empirical root-cause. He wants me to act as 1000 developers + every domain, day & night, on ONE product, focusing on every micro to nano detail AUTOMATICALLY, taking his input as ROUGH INTENT only. He has EXISTING autonomy docs that DID NOT prevent this (the enforcement gap is the real problem). Read: C:/Users/kunal/Desktop/caps/CLAUDE.md, START_HERE.md, MAX_AUTONOMY_PROMPT.md, BUILD_TREE_PROTOCOL.md, ULTRACODE_UNIVERSE.md, AUTONOMY_OS.md, the memory dir C:/Users/kunal/.claude/projects/C--Users-kunal-desktop-caps/memory/ (esp. act-as-independent-team-empirical-first.md, production-grade-build-pipeline.md, ownership-and-real-working-verification.md), and CONTINUE-HERE-ROUND7.md (today's incident). ANTI-IRONY RULE: the output must be SHARP + ENFORCEABLE + concise - a bloated generic doc would BE the failure it is meant to fix.";

phase('DiagnoseResearch')
const r = await parallel([
  () => agent(CTX + "\nPOST-MORTEM of today: from CONTINUE-HERE-ROUND7.md + EARNER-LIVE-STATE.md + this project recent history, extract the EXACT decision points where I went wrong and the right move I skipped. Map each to a root behavioral cause (followed-a-guess / premature-done / no-empirical-proof-first / thrash / generic-build / missed-nano-detail). Output a precise failure list -> the specific guardrail each one needs.", {label:'diag:postmortem', phase:'DiagnoseResearch', model:'opus', effort:'high', agentType:'Explore'}),
  () => agent(CTX + "\nAUDIT the EXISTING autonomy system (MAX_AUTONOMY_PROMPT.md, BUILD_TREE_PROTOCOL.md, ULTRACODE_UNIVERSE.md, AUTONOMY_OS.md, START_HERE.md, CLAUDE.md, the memories). What do they already mandate? WHY did they FAIL to prevent today (the enforcement gap - principles exist but nothing forced me to follow them under pressure)? What is redundant/bloated vs missing? Output: keep / cut / add, and the specific ENFORCEMENT missing.", {label:'diag:audit', phase:'DiagnoseResearch', model:'opus', effort:'high', agentType:'Explore'}),
  () => agent(CTX + "\nWEB-RESEARCH (cite): how do ELITE engineering orgs + autonomous-agent systems guarantee COMPLETENESS + RIGOR - RFC/design-review/ADR culture, Definition-of-Done, code-review/red-team gates, SRE/production-readiness reviews, you-build-it-you-run-it. What concretely PREVENTS shipping incomplete/unverified work? Return the transferable mechanisms.", {label:'res:elite', phase:'DiagnoseResearch', model:'sonnet', effort:'high', agentType:'Explore'}),
  () => agent(CTX + "\nWEB-RESEARCH (cite): the COMPLETE PRODUCTION-READINESS checklist - the nano-details a non-technical founder will not ask for but every build needs. Cover FRONTEND (pagination/virtualized lists, lazy-load, loading/empty/error states, optimistic UI, a11y, responsive), BACKEND (authz+authn, input validation, rate-limiting, idempotency, pagination, N+1/indexing, caching, timeouts/retries/circuit-breakers, transactions), DATA (migrations, constraints, backups), SECURITY (secrets, least-privilege, injection, RLS/multi-tenant isolation), OPS/OBSERVABILITY (structured logs, metrics, health checks, alerts, graceful rollback), QUALITY (tests, error budgets), COST/scale. Return it as a CONCISE, checkable list grouped by layer.", {label:'res:checklist', phase:'DiagnoseResearch', model:'sonnet', effort:'high', agentType:'Explore'}),
  () => agent(CTX + "\nWEB+REASON: how to serve a NON-TECHNICAL founder who gives a rough sketch - (a) INTENT-EXTRACTION (find the true goal behind imperfect words), (b) REQUIREMENT-COMPLETION (build what they need but did not name), (c) how to NOT execute their wrong/beginner solutions while fully respecting their goal + autonomy (disagree-with-the-fix-not-the-goal; prove before pivoting). Return concrete operating rules + phrasing patterns.", {label:'res:founder', phase:'DiagnoseResearch', model:'sonnet', effort:'high', agentType:'Explore'}),
  () => agent(CTX + "\nENFORCEMENT research: what can ACTUALLY force the new behavior in Claude Code (not just a doc that gets ignored under pressure)? Investigate hooks (PreToolUse/PostToolUse/Stop/SessionStart/PreCompact - what is gateable; can a hook inject a have-you-proven-it-on-the-real-flow reminder before a Stop/done, or a production-readiness reminder on edits?), a SessionStart binding that loads the protocol, a mandatory pre-build build-spec step, the verify-before-done GATE. Look at the user existing hooks (C:/Users/kunal/.claude/hooks/ + settings). Return the concrete enforcement mechanisms that are actually implementable + how.", {label:'res:enforce', phase:'DiagnoseResearch', model:'opus', effort:'high', agentType:'Explore'}),
])

phase('Design')
const design = await agent(CTX + "\nSYNTHESIZE the OPERATING SYSTEM from the diagnosis+research below. It must be SHARP + ENFORCEABLE (anti-bloat). Specify exactly: (A) THE CORE LOOP for any founder request: extract-intent -> research production requirements -> design (multi-domain) -> red-team -> build COMPLETE (auto-apply the readiness checklist) -> VERIFY empirically on the real flow -> only then done. (B) THE 3 HARD GATES (non-negotiable): #1 INTENT-NOT-SPEC (build the complete production thing, auto-include nano-details); #2 PROVE-DONT-OBEY (never execute a guessed fix - founder or mine - without empirical proof of the real cause); #3 VERIFY-BEFORE-DONE (no done/test-it without proof on the real flow). (C) the MULTI-DOMAIN roles engaged per build (arch/security/perf-scale/data/frontend-UX/resilience/test/observability/product) + when to fan them out via the reusable workflow. (D) the ENFORCEMENT plan (which hooks, the SessionStart binding, the gate). (E) exactly which FILES to write/edit in the Build phase + a one-paragraph PLAIN-LANGUAGE summary for the non-technical founder of what changes in how I work. Keep each artifact LEAN.\n\nDIAGNOSIS+RESEARCH:\n" + r.map((x,i)=>"["+i+"] " + String(x||'').slice(0,2200)).join('\n\n'), {label:'design:os', phase:'Design', model:'opus', effort:'high'})

phase('Build')
const built = await parallel([
  () => agent(CTX + "\nWRITE the binding protocol file C:/Users/kunal/Desktop/caps/AUTONOMOUS_ENGINEERING_OS.md per the design below - CONCISE + ENFORCEABLE: the core loop, the 3 hard gates (intent-not-spec / prove-dont-obey / verify-before-done), the multi-domain roles, when to invoke the production-build workflow, and a short PLAIN-LANGUAGE founder summary at the top. Then add a TIGHT binding block (<=12 lines) to the TOP of C:/Users/kunal/Desktop/caps/CLAUDE.md AND C:/Users/kunal/.claude/CLAUDE.md pointing every session to this OS + the 3 gates. Do NOT bloat. Report what you wrote.\n\nDESIGN:\n" + String(design||'').slice(0,5000), {label:'build:protocol', phase:'Build', model:'opus', effort:'high'}),
  () => agent(CTX + "\nWRITE C:/Users/kunal/Desktop/caps/PRODUCTION_READINESS_CHECKLIST.md = the definition of done (the nano-details the founder will not ask for) as a CONCISE, checkable list grouped by layer (frontend / backend / data / security / ops-observability / quality / cost-scale) - the things I must AUTO-build into every feature (pagination, lazy-load, loading/empty/error states, authz, validation, rate-limit, idempotency, N+1/indexing, caching, retries/timeouts, logs/metrics/health, rollback, tests, multi-tenant isolation, secrets). Make it usable as a pre-ship gate. Use the checklist research below. Report what you wrote.\n\nRESEARCH:\n" + String(r[3]||'').slice(0,3500), {label:'build:checklist', phase:'Build', model:'sonnet', effort:'high'}),
  () => agent(CTX + "\nMAKE THE ENFORCEMENT REAL. (1) Save a REUSABLE production-build workflow to C:/Users/kunal/Desktop/caps/.claude/workflows/production-build.md (or the correct workflows dir) - a parameterized ultracode pipeline: intent -> research -> multi-domain design -> red-team -> build -> verify, that I invoke for every substantive build so completeness is STRUCTURAL. (2) Implement the FEASIBLE hooks per the enforcement research (e.g., a SessionStart hook that surfaces the 3 gates + OS pointer; a Stop/PreCompact reminder to verify-before-done; a PostToolUse reminder on code edits to check the readiness checklist) - write the hook scripts + wire them in settings, MINIMAL + safe, test they do not break the session. (3) Update/extend the memory act-as-independent-team-empirical-first.md + add a memory pointer for the OS. Report exactly what you created + how it enforces the 3 gates.\n\nDESIGN:\n" + String(design||'').slice(0,4000) + "\nENFORCEMENT RESEARCH:\n" + String(r[5]||'').slice(0,2500), {label:'build:enforce', phase:'Build', model:'opus', effort:'high'}),
])

phase('RedTeam')
const red = await agent(CTX + "\nRED-TEAM the operating system just built (files below). REPLAY today actual incident through it step-by-step: at each point where I failed (executed the penalty guess; said done unverified ~10x; thrashed keys/reverts; missed that the prompt-bloat was the cause; would-have-missed pagination/lazy-load on an app) - would the new OS + gates + hooks + checklist have STOPPED me and forced the right move? For each failure: PREVENTED (how) or STILL-SLIPS-THROUGH (the gap). Close any gap by specifying the exact fix. Then give a TIGHT (<=250w) FINAL REPORT for the founder: what concretely changed in how I work, the 3 gates, where they are enforced, and an honest statement of what still depends on my discipline vs what is now mechanically enforced.\n\nBUILT:\n" + built.map((x,i)=>"["+i+"] " + String(x||'').slice(0,1800)).join('\n\n'), {label:'redteam:os', phase:'RedTeam', model:'opus', effort:'high'})

return { diagnosed:r.filter(Boolean).length, designed:!!design, built:built.filter(Boolean).length, redteam: red }
