export const meta = {
  name: 'round8-key-architecture',
  description: 'Production-grade, CAREFUL fix for the voice dead-air: design + build + verify the correct Groq key architecture (sticky-per-call + load-spread across all keys + instant 429-fallback + prompt-cache-preserving) PLUS the token-waste cut (sliding-window history + gate aux calls). Full pipeline: explore -> web-research -> design -> red-team -> build (earner-safe, voice byte-identical) -> independent verify. The brain (golden 5c055a31 + lean 4ae81ac6) is PROVEN good and stays untouched. No breakage: verified on the box before the founder tests.',
  phases: [
    { title: 'Explore', detail: 'map the key lifecycle + token path + cache/latency in the live code (read-only)' },
    { title: 'Research', detail: 'web: Groq prompt-cache mechanics + multi-key pool patterns + short-response token architecture' },
    { title: 'Design', detail: 'design the architecture + adversarial red-team' },
    { title: 'Build', detail: 'reconcile to golden, apply minimal earner-safe change, offline-verify' },
    { title: 'Verify', detail: 'independent red-test on the box: key-spread + 429-fallback + latency + voice byte-identical' },
  ],
}
const BASE = "EARNER-CRITICAL, production-grade, CAREFUL (the founder has suffered repeated breakage today - do NOT break the earner; voice BYTE-IDENTICAL; PROVE on the box before any founder test). GOAL: a correct low-latency Groq key architecture that ENDS the voice dead-air for good while the brain stays the real telecaller. PROVEN ROOT CAUSE (diagnostic + var/usage_events.json + journalctl): dead-air = Groq per-DAY token (TPD) 429 because (1) THE FORK-INDEX-0 BUG: _GROQ_CYCLE = itertools.cycle(...) is module-level so each forked LiveKit worker copies it at index 0 -> EVERY call hits key #1 (GROQ_API_KEY) -> that ONE org pegs at 499K/500K while ~13 other keys sit IDLE; (2) TOKEN WASTE: the per-turn LLM context re-sends the growing transcript (quadratic deep in long calls) + 3 aux Groq calls per call (_llm_opener, _summarize, _llm_close); today input=2.79M vs output=42K. The BRAIN WORKS - golden agent.py 5c055a31 + lean prompt 4ae81ac6 (4 good turns proven live; red-team verified 0 percent loop + cross-vertical + books a visit) - LEAVE IT UNTOUCHED. FOUNDER ARCHITECTURE INSIGHT (validated; adopt as a strong prior but confirm with research): ONE key per CALL is plenty (500K/day is huge vs the few-K a call needs once waste is fixed); STICKY-per-call PRESERVES Groq's prompt cache (lower latency; switching keys mid-call cold-starts the cache); switch keys ONLY on a 429 (instant fallback); SPREAD load ACROSS calls (call#1->keyA, call#2->keyB) over ~15 keys = ~7.5M tokens/day. Box: famit@168.144.153.145, /opt/famit-agent/, key ~/.ssh/do-blr-test/id_ed25519 - USE PowerShell scp+ssh, stage bash scripts to FILES (inline quoting mangles). LIVE: agent.py golden 5c055a31, prompt.py lean 4ae81ac6, ~14 .env GROQ keys, GROQ_MAX_TOKENS=90, KERNEL_OUTBOUND=0, EL_STABILITY=0.55. THE LAW: voice BYTE-IDENTICAL (TTS constructor / .env EL_STABILITY=0.55 / voice_id NEVER touched); prompt.py UNTOUCHED; agent.py edits = key-selection + token-window ONLY; py_compile under /opt/capsy-agent/.venv/bin/python; back up before any change; rollback armed; the founder's REAL call is the only truth - do NOT claim done.";

phase('Explore')
const ex = await parallel([
  () => agent(BASE + " [EXPLORE key-lifecycle] Map the FULL Groq key lifecycle in the live agent.py 5c055a31 (read it on the box), file:line: _collect_groq_keys (how keys load + dedup), _GROQ_CYCLE / _next_groq_key (the module-level itertools.cycle fork-index-0 bug), exactly WHERE the key is chosen (per call? frozen for the call? per turn?), the 429 retry path (how many retries, same key or switch), any cooldown. Output the precise spots + the minimal way to: spread the pick across ALL keys per-call (fork-safe, e.g. seed by job/room id or a persisted round-robin counter, NOT a module cycle), keep it STICKY for the whole call, and switch only on a 429.", {label:'ex:keys', phase:'Explore', model:'opus', effort:'high', agentType:'Explore'}),
  () => agent(BASE + " [EXPLORE token-path] Map the per-turn LLM context assembly + the 3 aux Groq calls in agent.py 5c055a31 (file:line): how the conversation history is built into the messages each turn (does it grow unbounded / quadratic deep in a call?), and _llm_opener / _summarize / _llm_close (what each sends, how big, per-call or per-turn). Identify the minimal brain-SAFE change to: cap history to a sliding window of recent turns, and gate/disable _summarize (the whole-transcript re-send). Confirm prompt.py is NOT involved (it stays untouched).", {label:'ex:tokens', phase:'Explore', model:'opus', effort:'high', agentType:'Explore'}),
  () => agent(BASE + " [EXPLORE cache+latency] From the live code + logs: how does Groq prompt-caching apply here (the static system-prompt prefix), and what is the REAL per-turn latency (parse LATENCY log lines: eou_delay, llm_ttft, tts_ttfb)? Does the lean prompt + a stable per-call key help the cache? Quantify current latency + where sticky-per-call vs per-turn key switching would help or hurt it. file:line + numbers.", {label:'ex:cache', phase:'Explore', model:'opus', effort:'high', agentType:'Explore'}),
])
const EX = ex.map(function(x,i){return '[ex'+i+'] ' + String(x||'').slice(0,2000)}).join('\n\n')

phase('Research')
const re = await parallel([
  () => agent(BASE + " [RESEARCH groq-cache] WEB-SEARCH (cite URLs): Groq prompt-caching - how is it keyed (per API key? per org? the prompt prefix?), what preserves vs breaks it, the latency/cost benefit, and does switching API keys mid-conversation lose the cache? Validate or correct the founder's insight that sticky-per-call preserves the cache. Return concrete findings.", {label:'re:cache', phase:'Research', model:'sonnet', effort:'high', agentType:'Explore'}),
  () => agent(BASE + " [RESEARCH key-pool] WEB-SEARCH (cite): production multi-API-key LLM pool patterns - sticky-per-call vs per-turn rotation, least-used / round-robin load distribution, instant 429 fallback honoring Retry-After, per-key health/cooldown, avoiding thundering-herd, and the FORKED-worker pitfall (a module-level cycle resets to index 0 in each fork - how production systems avoid it). Return the concrete recommended pattern for ~15 keys + a forked LiveKit worker model.", {label:'re:pool', phase:'Research', model:'sonnet', effort:'high', agentType:'Explore'}),
  () => agent(BASE + " [RESEARCH token-arch] WEB-SEARCH (cite): the right token architecture for a SHORT-RESPONSE real-time voice agent - sliding-window vs full-transcript history, the cost of re-sending history each turn, summarization trade-offs, minimizing per-turn input for low latency. What window size is standard? Return the recommended approach.", {label:'re:token', phase:'Research', model:'sonnet', effort:'high', agentType:'Explore'}),
])
const RE = re.map(function(x,i){return '[re'+i+'] ' + String(x||'').slice(0,2000)}).join('\n\n')

phase('Design')
const dz = await parallel([
  () => agent(BASE + " [DESIGN] Synthesize the EXPLORE + RESEARCH below into THE ARCHITECTURE with an exact file:line implementation plan, MINIMAL + earner-safe: (a) KEY ARCH - fix the fork-index-0 bug so each CALL picks a key that spreads across all ~15 keys (fork-safe: seed by room/job id or a small persisted least-used counter), STICKY for the whole call (preserve Groq cache), switch ONLY on a 429 -> instant re-pick of a healthy key (no other mid-call churn); (b) TOKEN - cap history to a sliding window of recent turns + gate _summarize. Confirm voice byte-identical + prompt.py untouched. Give the exact diff hunks + an offline test plan. Reconcile the founder's sticky-cache insight with the research (adopt if confirmed).\n\nEXPLORE:\n" + EX + "\n\nRESEARCH:\n" + RE, {label:'dz:design', phase:'Design', model:'opus', effort:'high'}),
  () => agent(BASE + " [RED-TEAM] Adversarially review the architecture the design agent is producing (same EXPLORE+RESEARCH inputs). Where could it BREAK the voice/earner? latency regression? cache miss? race conditions in the key counter across forked workers? edge cases: ALL keys 429 (graceful?), a key dies mid-call, the round-robin counter corrupts, a restart? Does it stay voice byte-identical? For EACH risk: the gate/test that must pass before deploy. Be harsh - the founder cannot afford another break.\n\nEXPLORE:\n" + EX + "\n\nRESEARCH:\n" + RE, {label:'dz:redteam', phase:'Design', model:'opus', effort:'high'}),
])
const DESIGN = String(dz[0]||'').slice(0,6000)
const REDTEAM = String(dz[1]||'').slice(0,3000)

phase('Build')
const build = await agent(BASE + " [BUILD - careful, earner-safe] FIRST reconcile the earner to golden: verify live agent.py md5 = 5c055a31 + prompt.py = 4ae81ac6 (a prior stopped agent may have left a half-state - if so, restore golden from backups before building). Back up agent.py + .env. Apply the DESIGN below (key-spread + sticky + 429-instant-fallback + sliding-window history + gate _summarize) - MINIMAL surgical hunks, voice byte-identical (assert TTS-span md5 before==after), prompt.py UNTOUCHED. OFFLINE-VERIFY before restart (iterate until all green, honoring the RED-TEAM gates): py_compile + import; replay 8+ turns -> conversation coherent + no-loop + per-call burn bounded; simulate the forked-worker model -> different calls pick DIFFERENT keys (spread, not all key#1); simulate a 429 on the active key -> instant re-pick of a healthy key, no surfaced error, sticky otherwise. Only if all green: restart famit-agent, verify active/NRestarts=0/0 errors/voice byte-identical. Auto-rollback on any failure. Record at the TOP of C:/Users/kunal/Desktop/caps/EARNER-LIVE-STATE.md with a one-command rollback. Report file:line changes + the offline proofs.\n\nDESIGN:\n" + DESIGN + "\n\nRED-TEAM GATES:\n" + REDTEAM, {label:'build:apply', phase:'Build', model:'opus', effort:'high'})

phase('Verify')
const ver = await agent(BASE + " [VERIFY - independent red-test of the deployed build below] On the box, INDEPENDENTLY prove: (1) KEY SPREAD - simulate/observe multiple calls -> they use DIFFERENT keys across the ~15 (not all key #1); (2) 429 INSTANT-FALLBACK - force a 429 on the active key -> the call instantly continues on a fresh healthy key, no dead-air, sub-second switch; (3) NO DEAD-AIR / brain - replay a full 8-10 turn conversation -> coherent telecaller (greets, pitches, asks, negotiates, books a visit), no loop, per-call token burn bounded + well under one key's daily budget; (4) LATENCY - no regression vs baseline (eou/llm_ttft/tts_ttfb); (5) VOICE byte-identical (TTS-span md5, EL_STABILITY=0.55, voice_id); (6) all keys/index-0 have budget. Update EARNER-LIVE-STATE.md + C:/Users/kunal/Desktop/caps/CONTINUE-HERE-ROUND7.md with the FINAL state + rollback. Return a TIGHT (<=300 word) summary: the proven fix, the key-spread proof, the 429-fallback proof, the latency numbers, what the founder must test (ONE real full call), and an HONEST note that only his real call is final truth. Do NOT auto-place a real outbound call (spam/cost risk) - the founder places it.\n\nBUILD RESULT:\n" + String(build||'').slice(0,3500), {label:'verify:redtest', phase:'Verify', model:'opus', effort:'high'})

return { explored: ex.filter(Boolean).length, researched: re.filter(Boolean).length, designed: !!dz[0], built: !!build, final: ver }
