export const meta = {
  name: 'round9-brain-plan',
  description: 'READ-ONLY deep planning ultracode for the VOICE BRAIN: map the brain code (prompt + booking/closing/turn-detection + memory) + web-research master 30-year telecaller technique + root-cause the known brain bugs (AUTO-BOOKING: AI says "booked the site visit" with NO user ask and NO user reply; AUTO-CUT: call ends right after) + design the perfect real-human salesperson brain + red-team it. NO box mutation (plan mode). Returns a proven diagnosis + a concrete design + the exact files to change, for the main loop to turn into the plan + ExitPlanMode. The dead-air + loop are ALREADY FIXED; this is brain-quality only.',
  phases: [
    { title: 'ExploreBrain', detail: 'map prompt + booking/closing + turn-detection + memory + trace the auto-booking (read-only)' },
    { title: 'Research', detail: 'web: master telecaller structure + sales-prompt technique + voice turn-taking + objection/curiosity' },
    { title: 'Design', detail: 'diagnose root causes + design the perfect telecaller brain + red-team' },
    { title: 'Synthesize', detail: 'proven diagnosis + concrete design + files-to-change' },
  ],
}
const BASE = "VOICE BRAIN PLANNING (READ-ONLY — mutate NOTHING; this is plan mode). The dead-air (Groq key fork-bug) and the 'haan haan' loop are ALREADY FIXED and live. NOW the goal is making the BRAIN a crazy-level REAL-HUMAN 30+ YEAR TELECALLER/salesperson: opens, builds rapport, makes the prospect CURIOUS, discovers needs, pitches step-by-step, answers, handles objections, trial-closes, and books a site visit ONLY when the prospect explicitly agrees, then closes naturally — driving the person toward BUYING, never robotic. KNOWN BRAIN BUGS (founder + call transcripts): (1) AUTO-BOOKING — the AI says 'I have booked the site visit' with NO user request AND when the user did not even reply (it auto-generates the booking/confirmation); (2) AUTO-CUT — the call ends right after that phantom booking; (3) it sometimes responds with no user input. The brain surfaces: prompt.py (lean 4ae81ac6 — the system prompt that defines behavior), agent.py 5c055a31-derived (the booking tool/function, the closing/hangup/_llm_close logic, the VAD/turn-detection/endpointing, the opener, the per-turn flow), and the memory/context system (lead memory + conversation history injection). Box (READ-ONLY): ssh -i ~/.ssh/do-blr-test/id_ed25519 famit@168.144.153.145, /opt/famit-agent/ (use PowerShell ssh). Also read C:/Users/kunal/Desktop/caps/CONTINUE-HERE-ROUND7.md, design/GENIUS-TELECALLER-PROMPT.md, the recent call transcripts. THE LAW: voice/TTS/.env are PERFECT and LOCKED — the brain is prompt.py + the agent.py conversation logic (booking/closing/turn) ONLY. Reason as a 30-year master telecaller about every line.";

phase('ExploreBrain')
const ex = await parallel([
  () => agent(BASE + " [EX prompt] Read the LIVE lean system prompt (prompt.py build_system_prompt, md5 4ae81ac6) on the box IN FULL. Quote the exact instructions about: the conversation flow, booking, closing/ending, and how it tells the AI to behave. WHAT in the prompt could make the AI prematurely say 'I have booked the site visit' (without the user asking) or close early or be over-eager? Identify the over-eager/assume-booking/premature-close language. file:line + quotes.", {label:'ex:prompt', phase:'ExploreBrain', model:'opus', effort:'high', agentType:'Explore'}),
  () => agent(BASE + " [EX booking+closing] Read agent.py on the box: find the BOOKING tool/function (how a site-visit booking is detected, triggered, confirmed, persisted) and the CLOSING/HANGUP logic (_llm_close, goodbye/_goodbye_line, any 'end call'/disconnect trigger, the closure-on-turn logic). Does booking or closing auto-fire from a keyword, an LLM phrase, a turn event, or a tool call WITHOUT the user explicitly agreeing? Trace the exact trigger chain for both. file:line.", {label:'ex:bookclose', phase:'ExploreBrain', model:'opus', effort:'high', agentType:'Explore'}),
  () => agent(BASE + " [EX turn-detection] Read agent.py: the AgentSession / VAD / turn-detection / endpointing / preemptive_generation / min_endpointing_delay config. THE KEY QUESTION: can the AI generate a response when the user is SILENT / did not reply (a timeout, an endpointing fire on a pause, a preemptive generation, an empty-turn) — which would explain 'the AI auto-responded even though I did not reply'? Trace whether silence/empty-input can trigger an LLM turn. file:line.", {label:'ex:turn', phase:'ExploreBrain', model:'opus', effort:'high', agentType:'Explore'}),
  () => agent(BASE + " [EX autobook-trace] From the recent call transcripts (in CONTINUE-HERE / the panel) + journalctl on the box, find a call where the AI said 'booked the site visit' WITHOUT the user asking/replying. Trace the EXACT sequence: what was the prior user turn (or was it silence?), what did the LLM receive, what made it emit the booking+close. Pin the trigger: prompt-eagerness vs a silence-triggered turn vs a tool vs hallucination. Quote the log lines.", {label:'ex:trace', phase:'ExploreBrain', model:'opus', effort:'high', agentType:'Explore'}),
  () => agent(BASE + " [EX memory] Map the memory/context system: lead memory, conversation history, any per-call injected context (does the brain get prior-call data, a 'booking' flag, lead profile?). Is it correct, or could it inject something (e.g. a stale booking, wrong lead state) that makes the AI think a booking happened or skip steps? The founder is unsure the memory is perfect — assess it. file:line.", {label:'ex:memory', phase:'ExploreBrain', model:'opus', effort:'high', agentType:'Explore'}),
  () => agent(BASE + " [EX flow] Map the overall conversation-flow control in agent.py + the opener: how the brain drives open->pitch->objection->book->close, what state it tracks, and where the flow can skip ahead (jump to booking/closing) prematurely. Also note any latency/turn-taking issues that hurt the human feel. file:line.", {label:'ex:flow', phase:'ExploreBrain', model:'opus', effort:'high', agentType:'Explore'}),
])
const EX = ex.map(function(x,i){return '[ex'+i+'] ' + String(x||'').slice(0,1700)}).join('\n\n')

phase('Research')
const re = await parallel([
  () => agent(BASE + " [RE telecaller] WEB-RESEARCH (cite): the structure + psychology of a GREAT real-estate / high-ticket-product telecaller call — opening hook, rapport, discovery questions, step-by-step pitch, creating curiosity + desire, urgency/scarcity, trial-close, asking for the site-visit/appointment, and the natural close. What does a 30-year top closer DO at each stage? Return a concrete stage-by-stage playbook.", {label:'re:tele', phase:'Research', model:'sonnet', effort:'high', agentType:'Explore'}),
  () => agent(BASE + " [RE sales-prompt] WEB-RESEARCH (cite): LLM/voice-AI prompt techniques for a SALES/telecaller agent that behaves human and never robotic — how to make it ASK before assuming, CONFIRM before taking an action (never auto-book), drive discovery, handle objections by principle (not script), build curiosity, and advance to the next step. Patterns that prevent an LLM from hallucinating a completed action (e.g. 'I have booked...') and from ending the call early. Return concrete prompt rules.", {label:'re:prompt', phase:'Research', model:'sonnet', effort:'high', agentType:'Explore'}),
  () => agent(BASE + " [RE voice-turn] WEB-RESEARCH (cite): voice-agent turn-taking + action-confirmation best practices — never respond on silence/empty input, confirm an action verbally before doing it, natural backchanneling, not cutting the user off, and how top voice agents (Bland/Vapi/Retell/PolyAI) structure booking/scheduling so it only happens on explicit user agreement. Return concrete dos/donts.", {label:'re:voice', phase:'Research', model:'sonnet', effort:'high', agentType:'Explore'}),
  () => agent(BASE + " [RE objection-curiosity] WEB-RESEARCH (cite): objection-handling frameworks (price, trust, timing, 'let me think') + curiosity/engagement techniques that keep a prospect IN the conversation and move them toward a visit/purchase, for real estate + products. Return concrete techniques a brain prompt can embody.", {label:'re:obj', phase:'Research', model:'sonnet', effort:'high', agentType:'Explore'}),
])
const RE = re.map(function(x,i){return '[re'+i+'] ' + String(x||'').slice(0,1700)}).join('\n\n')

phase('Design')
const dz = await parallel([
  () => agent(BASE + " [DIAGNOSE] From the EXPLORE findings below, state the PROVEN root cause of each brain bug: (1) the AUTO-BOOKING ('I have booked' with no user ask/reply) — is it prompt-eagerness, a silence-triggered LLM turn, a booking tool auto-fire, or hallucination? (2) the AUTO-CUT after booking; (3) responding with no user input. Rank by severity + give the exact fix locus (prompt vs agent.py turn-detection vs booking/closing logic) file:line.\n\nEXPLORE:\n" + EX, {label:'dz:diag', phase:'Design', model:'opus', effort:'high'}),
  () => agent(BASE + " [DESIGN the perfect telecaller brain] Using the EXPLORE + RESEARCH below, design the brain so it behaves like a 30-year master closer: the full conversation flow (open->hook->rapport->discovery->step-pitch->objection-handle->curiosity/desire->trial-close->ASK for the visit->book ONLY on explicit user yes->natural close), the exact prompt rewrite (what to add/cut/reword in prompt.py to fix the eagerness + add the master-closer behavior, while staying LEAN to avoid the loop), and the agent.py logic guards (never book/close without explicit user agreement; never respond on silence). Give a concrete prompt structure + the agent.py guard changes, file:line. Keep it earner-safe + voice-untouched.\n\nEXPLORE:\n" + EX + "\n\nRESEARCH:\n" + RE, {label:'dz:design', phase:'Design', model:'opus', effort:'high'}),
  () => agent(BASE + " [RED-TEAM] Harshly red-team the brain design being produced (same inputs): does the new prompt risk re-introducing the loop (too long/bloated)? does it still over-book or under-book? does it handle a user who says 'maybe later' / 'too expensive' / silence / wrong-number? could the agent.py guards break the flow or the voice? does it stay a real human (not robotic, not pushy)? For each risk, the test that must pass. Be ruthless — the founder needs a flawless closer.\n\nEXPLORE:\n" + EX + "\n\nRESEARCH:\n" + RE, {label:'dz:redteam', phase:'Design', model:'opus', effort:'high'}),
])

phase('Synthesize')
const syn = await agent(BASE + " [SYNTHESIZE the brain plan] Fuse the diagnosis + design + red-team below into a TIGHT, executable plan the main loop will put in the plan file: (A) PROVEN root causes of the auto-booking + auto-cut + over-response (file:line); (B) THE PERFECT-TELECALLER BRAIN design — the conversation flow + the exact prompt.py rewrite approach (lean, master-closer, never-auto-book) + the agent.py guards (no book/close/response without explicit user input) — file:line; (C) the build approach (earner-safe, voice-untouched, prompt.py + minimal agent.py guards, ONE wave, real-call gated); (D) the verification (a real founder call: full human conversation, books ONLY on a real yes, never auto-cuts). Return the full plan text.\n\nDIAGNOSE:\n" + String(dz[0]||'').slice(0,3500) + "\n\nDESIGN:\n" + String(dz[1]||'').slice(0,4500) + "\n\nRED-TEAM:\n" + String(dz[2]||'').slice(0,2500), {label:'syn:plan', phase:'Synthesize', model:'opus', effort:'high'})

return { explored: ex.filter(Boolean).length, researched: re.filter(Boolean).length, designed: dz.filter(Boolean).length, plan: syn }
