export const meta = {
  name: 'round9-secure-git-save',
  description: 'SAVE the current working system to GitHub securely + build a one-command restore system, BEFORE any brain change. Security-scan is a HARD GATE (no secret ever pushed). Pushes the ~1 week of unpushed local commits + a milestone branch/tag, snapshots a secrets-stripped working-brain to an earner-golden branch + an on-box golden + a restore script, and makes regular secure pushing a standing rule. The voice (dead-air + loop + key-arch) is fixed + working - this preserves it so any future break reverts in seconds.',
  phases: [
    { title: 'Security', detail: 'gitleaks + secret-scan; HARD GATE - abort the push if ANY secret would leak' },
    { title: 'Push', detail: 'commit + push the local history + current state + a milestone branch/tag' },
    { title: 'EarnerRestore', detail: 'secrets-stripped working-brain snapshot to GitHub + on-box golden + 1-command restore' },
    { title: 'Habit', detail: 'standing rule: regular secure GitHub push, to memory + CLAUDE.md' },
  ],
}
const BASE = "SAVE the CURRENT WORKING STATE to GitHub + a restore system, BEFORE any brain change (founder's #1). The voice is FIXED (dead-air + 'haan' loop + key-spread architecture) and working; preserve it. Repo: https://github.com/kunal-7x/axcrio-platform.git . Local repo / working dir: C:/Users/kunal/desktop/caps . There are LOCAL commits not pushed since ~1 week ago - push them all. SECURITY IS PARAMOUNT - NEVER commit/push a secret. Secret files that must NEVER be committed (the .gitignore + gitleaks are the net): .env, .env.local, final_env.md, any **/ALL_CREDENTIALS.md, ai_manager_cred.md, groq_api.md, z_groq_api.md, fortress/cred.md, infra/logto/app_id_secret*, the SSH key id_ed25519, any *.key / token / *cred* / *secret* file, and any inline gsk_/sk-/Bearer/password value. The GitHub token is in .env.local (use it for auth: gh CLI or a tokenized git remote; do NOT print the token). The LIVE voice earner (agent.py md5 11a865fe + prompt.py 4ae81ac6) lives on the box /opt/famit-agent (git-IGNORED, secret-risk) - it is NOT in the repo; for restore, snapshot a SECRETS-STRIPPED copy to a GitHub branch. Per project CLAUDE.md: branch, never force-push main; `gitleaks protect --staged` must be 0 before every commit. Use PowerShell + git/gh. Box read: ssh -i ~/.ssh/do-blr-test/id_ed25519 famit@168.144.153.145.";

phase('Security')
const sec = await agent(BASE + " [SECURITY - HARD GATE] Run gitleaks (or a thorough secret-scan) on the repo working tree AND exactly what a commit-all would stage. List EVERY file that would be committed; CONFIRM none is a secret file (the list above) and there is no inline secret (gsk_/sk-/Bearer/api_key/password/PRIVATE KEY patterns) in any tracked/to-be-tracked file. Verify .gitignore actually blocks every secret path. Return a crisp verdict: PASS (safe to push) with the file count + categories, OR ABORT with the exact offending file(s)/lines. `gitleaks protect --staged` must = 0. This verdict GATES the Push phase - if not clearly PASS, the push must not happen.", {label:'sec:scan', phase:'Security', model:'opus', effort:'high'})

phase('Push')
const push = await agent(BASE + " [PUSH] ONLY proceed if the SECURITY verdict below is PASS (if ABORT, do NOT push - report the blocker + stop). Then: `git status` + `git log origin/main..HEAD` (the local-not-pushed commits). `git add` the SAFE working files (design docs, plan files, famit-panel, growth-os, etc. - NEVER any secret file; re-confirm via git status before commit). Make a clear MILESTONE commit (message: 'milestone: working voice - dead-air + loop + Groq key-spread fixed (2026-06-21)'; end with the Co-Authored-By line). Push to origin (kunal-7x/axcrio-platform) using the .env.local token (never print it). Create a MILESTONE branch `milestone/working-voice-20260621` + an annotated tag, pushed. Run `gitleaks protect --staged`=0 immediately before the commit as the final net. Report the pushed commit SHA, branch, tag, and the file count - NOT any secret.\n\nSECURITY VERDICT:\n" + String(sec||'').slice(0,3000), {label:'push:milestone', phase:'Push', model:'opus', effort:'high'})

phase('EarnerRestore')
const er = await agent(BASE + " [EARNER RESTORE - the seconds-to-revert system the founder wants] Preserve the WORKING VOICE BRAIN so any future break reverts instantly, deployed-or-not. (1) From the box, take a SECRETS-STRIPPED snapshot of the live earner: agent.py (md5 11a865fe), prompt.py (4ae81ac6), the systemd drop-in with env VALUES removed (names-only ENV.example), llm_router if present - NO keys/.env values. Commit it to a GitHub branch `earner-golden` (gitleaks-clean) on kunal-7x/axcrio-platform with a README on how to restore. (2) Ensure an on-box golden dir /opt/famit-agent/_GOLDEN_R9_20260621/ holding agent.py+prompt.py+drop-in + a restore.sh that asserts the md5s + voice TTS-span + EL_STABILITY=0.55 before restarting (aborts on mismatch). (3) Write C:/Users/kunal/desktop/caps/RESTORE-SYSTEM.md: the exact one-command on-box restore + the GitHub earner-golden restore, for both 'deployed' and 'fresh-box' cases. Report what was created + the one-command restore.", {label:'er:golden', phase:'EarnerRestore', model:'opus', effort:'high'})

phase('Habit')
const hab = await agent(BASE + " [STANDING RULE - so I never stop pushing again] (1) Write a NEW memory file C:/Users/kunal/.claude/projects/C--Users-kunal-desktop-caps/memory/regular-git-push-and-restore.md (frontmatter type: feedback) capturing: 'commit + push to GitHub kunal-7x/axcrio-platform REGULARLY - at every milestone / verified-good state, not just locally; ALWAYS run gitleaks/security-scan BEFORE any push (never leak .env/keys/tokens/SSH key); use branches + full history; the git-ignored earner gets a SECRETS-STRIPPED snapshot to the earner-golden branch; a one-command restore (on-box golden + GitHub) must always exist. WHY: the founder caught that I committed only LOCALLY and stopped pushing to GitHub for ~a week - if a session/box died, the work + the restore point would be lost. HOW: after any verified milestone, security-scan -> commit -> push -> tag.' Add a one-line pointer to MEMORY.md. (2) Add a TIGHT binding line to C:/Users/kunal/.claude/CLAUDE.md AND C:/Users/kunal/desktop/caps/CLAUDE.md: 'After every verified milestone: security-scan then commit+push to GitHub (kunal-7x/axcrio-platform); keep a one-command restore.' Report what you wrote.", {label:'habit:rule', phase:'Habit', model:'opus', effort:'high'})

return { security: sec, pushed: push, restore: er, habit: hab }
