"""voice_ops.deploy.rollback — the ONE-COMMAND rollback generator.

Every deploy stages its own rollback BEFORE it flips anything (§8 of the manual
cutover). Given a DeployRecord (backup path, target, release dirs, the flag
drop-in), this produces:

  * `script()`   — a single idempotent bash script that:
       1. restores the backup file over the target (cp), OR re-points the
          `current` symlink to the previous release (atomic mv -T) when a
          release-dir layout is used,
       2. forces the feature flag OFF in the systemd drop-in,
       3. daemon-reload + restart ONLY the affected unit,
       4. re-asserts the earner gate (md5 back to golden, /health 200).
  * `execute()`  — runs that rollback through the transport (used by the
    auto-rollback path), returning the restored md5 for verification.

A rollback is ALWAYS staged before risk, so an interruption costs at most the
in-flight unit — recovery is one command, never archaeology.
"""
from __future__ import annotations

from dataclasses import dataclass

from .plan import DeployRecord
from .transport import ExecTransport


@dataclass
class RollbackTarget:
    """What a rollback must restore."""

    target_path: str            # e.g. /opt/famit-agent/agent.py
    backup_path: str            # e.g. /opt/famit-agent/agent.py.WOUTbak.<ts>
    golden_md5: str             # the earner golden the box must return to
    unit: str = "famit-agent"
    flag_dropin: str | None = None   # e.g. .../famit-agent.service.d/kernel-outbound.conf
    flag_name: str | None = None     # e.g. KERNEL_OUTBOUND
    health_url: str = "http://127.0.0.1:8209/health?deep=0"
    # optional release-dir rollback (preferred when atomic-swap layout is used)
    current_link: str | None = None
    previous_release_dir: str | None = None
    lock_path: str = "/opt/famit-agent/.deploy.lock"


@dataclass
class RollbackGenerator:
    target: RollbackTarget

    @classmethod
    def from_record(
        cls,
        rec: DeployRecord,
        *,
        golden_md5: str,
        unit: str = "famit-agent",
        flag_dropin: str | None = None,
        flag_name: str | None = None,
        health_url: str = "http://127.0.0.1:8209/health?deep=0",
        current_link: str | None = None,
        previous_release_dir: str | None = None,
    ) -> "RollbackGenerator":
        return cls(
            RollbackTarget(
                target_path=rec.target_path,
                backup_path=rec.backup_path,
                golden_md5=golden_md5,
                unit=unit,
                flag_dropin=flag_dropin,
                flag_name=flag_name,
                health_url=health_url,
                current_link=current_link,
                previous_release_dir=previous_release_dir,
            )
        )

    # -- the restore + flag-off commands (shared by script + execute) ------ #
    def _restore_cmds(self) -> list[str]:
        t = self.target
        cmds: list[str] = []
        if t.current_link and t.previous_release_dir:
            # preferred: atomic re-point of the symlink to the previous release
            tmp = f"{t.current_link}.tmp.$$"
            cmds.append(
                f"flock -w 30 {t.lock_path} -c "
                f"'ln -sfn {t.previous_release_dir} {tmp} && mv -T {tmp} {t.current_link}'"
            )
        else:
            # in-place restore of the backup over the target
            cmds.append(f"cp -p {t.backup_path} {t.target_path}")
        if t.flag_dropin and t.flag_name:
            # force the flag OFF in the drop-in (idempotent sed; 1->0)
            cmds.append(
                f"sed -i 's/^Environment={t.flag_name}=.*/Environment={t.flag_name}=0/' "
                f"{t.flag_dropin}"
            )
            cmds.append("systemctl daemon-reload")
        cmds.append(f"systemctl restart {t.unit}")
        return cmds

    def script(self) -> str:
        """A self-contained, idempotent one-command rollback bash script."""
        t = self.target
        body = "\n".join(self._restore_cmds())
        return f"""#!/usr/bin/env bash
# ONE-COMMAND ROLLBACK (auto-generated by voice_ops.deploy.rollback) for {t.unit}.
# Restores the earner to golden md5 {t.golden_md5} and forces the flag OFF.
set -euo pipefail

{body}

# re-assert the earner gate: md5 back to golden + /health 200
GOT=$(md5sum {t.target_path} | cut -d' ' -f1)
if [ "$GOT" != "{t.golden_md5}" ]; then
  echo "ROLLBACK VERIFY FAILED: {t.target_path} md5 $GOT != golden {t.golden_md5}" >&2
  exit 1
fi
CODE=$(curl -s -o /dev/null -w "%{{http_code}}" {t.health_url})
if [ "$CODE" != "200" ]; then
  echo "ROLLBACK VERIFY FAILED: {t.health_url} returned $CODE != 200" >&2
  exit 1
fi
echo "ROLLBACK OK: {t.unit} restored to golden {t.golden_md5}, /health 200"
"""

    def execute(self, transport: ExecTransport) -> str:
        """Run the rollback through the transport (auto-rollback path). Restores
        the backup/symlink, forces flag OFF, restarts, and returns the restored
        md5 (so the caller can assert it == golden)."""
        for cmd in self._restore_cmds():
            transport.run(cmd, check=True)
        return transport.md5(self.target.target_path)
