"""voice_ops.deploy.runbook — assembles the human RUNBOOK for one deploy.

Given the concrete parameters of a deploy (unit, target, golden md5, intended
md5, flag, release id, the rolling-drain steps), render a markdown runbook the
founder/operator can follow OR hand to a later automated driver. The runbook is
the same discipline the engine enforces, written out so a human can verify each
gate by eye. It includes the staged one-command rollback verbatim.
"""
from __future__ import annotations

from dataclasses import dataclass, field

from .rollback import RollbackGenerator


@dataclass
class RunbookSpec:
    unit: str
    target_path: str
    golden_md5: str
    intended_md5: str
    release_id: str
    flag_name: str
    flag_dropin: str
    health_url: str = "http://127.0.0.1:8209/health?deep=0"
    rolling_drain_steps: list[str] = field(default_factory=list)
    two_worker: bool = False


def render_runbook(spec: RunbookSpec, rollback: RollbackGenerator) -> str:
    drain_block = (
        "\n".join(f"   {s}" for s in spec.rolling_drain_steps)
        if spec.rolling_drain_steps
        else "   (single-worker drain: drain -> wait in-flight==0 -> restart)"
    )
    worker_note = (
        "TWO-WORKER mode: drain A while B serves (no capacity gap, held canary on the "
        "standby worker)."
        if spec.two_worker
        else "SINGLE-WORKER mode: draining drops outbound capacity until restart — see "
        "the 2nd-worker recommendation in design/W25-DEPLOY-SAFETY-RUNBOOK.md."
    )
    return f"""# DEPLOY RUNBOOK — {spec.unit} (release {spec.release_id})

> Generated by voice_ops.deploy.runbook. Every gate below is enforced in code by
> the deploy engine; this is the human-verifiable mirror. {worker_note}

## Invariants
- Earner golden md5 (pre): `{spec.golden_md5}`
- Intended-new-closure md5 (post): `{spec.intended_md5}`
- Target file: `{spec.target_path}`
- Feature flag: `{spec.flag_name}` in `{spec.flag_dropin}` (NEVER the shared .env)

## Steps
1. PREFLIGHT EARNER GATE — assert `md5sum {spec.target_path}` == `{spec.golden_md5}`,
   `systemctl show {spec.unit} -p MainPID` non-zero, `{spec.health_url}` == 200.
   ABORT on any mismatch (nothing has been mutated yet).
2. BACKUP FIRST — `cp -p {spec.target_path} {spec.target_path}.WOUTbak.<ts>`;
   verify backup md5 == current target md5.
3. COMPUTE INTENDED-NEW-CLOSURE md5 LOCALLY (golden + patch -> py_compile -> md5)
   == `{spec.intended_md5}`. (Done off-box, before upload.)
4. UPLOAD FLAG-OFF — stage into the release dir; assert landed md5 ==
   `{spec.intended_md5}`. Refuse to swap on any mismatch (catches a wrong /
   truncated file).
5. ATOMIC SWAP — `flock` the deploy lock; `ln -sfn <release> current.tmp && mv -T
   current.tmp current` (atomic rename; `current` is never partial).
6. FLAG-OFF SMOKE — restart ONLY {spec.unit}; `{spec.health_url}` 200; render the
   golden greeting and assert byte-identical to the backup (render-equality gate).
7. GRACEFUL DRAIN + RESTART (onto the swapped code):
{drain_block}
8. FLAG-ON FLIP — set `Environment={spec.flag_name}=1` in `{spec.flag_dropin}`;
   `systemctl daemon-reload`; restart {spec.unit}. Verify via `/proc/<pid>/environ`
   the flag is present on THIS unit's process and ABSENT on the other unit's.
9. HELD SYNTHETIC CANARY (no PSTN) — greeting render + tool dry-run + DB deep-health.
   Fail-closed: any failure triggers the auto-rollback below.
10. HEALTH WATCH + AUTO-ROLLBACK — watch {spec.unit} for the settle window; on
    non-200 (>= fail_threshold consecutive) OR canary fail, FIRE the rollback.
11. POSTFLIGHT EARNER GATE — md5 on box == `{spec.intended_md5}`, PIDs healthy,
    `{spec.health_url}` 200.

## ONE-COMMAND ROLLBACK (staged BEFORE step 8 — always ready)
```bash
{rollback.script()}
```
"""
