#!/usr/bin/env node
/**
 * Generate the typed event surface for `@growth-os/events` from the contract registry
 * (BUILD-SPEC P1 contracts-first: types are DERIVED from the schemas, never hand-drifted).
 *
 *   node tools/codegen/generate-types.mjs   (also run by `pnpm codegen` via generate.mjs)
 *
 * Emits `packages/events/src/generated/`:
 *   - payloads.ts : one TS interface per event payload schema + the frozen artifacts
 *                   (CIB/MediaPlan/ActionPlan) and their shared sub-schemas (Explanation,
 *                   CreativeDNA). Compiled in a SINGLE pass over a synthetic root so shared
 *                   $refs are emitted exactly ONCE (no duplicate-interface redeclarations).
 *   - catalog.ts  : EVENT_CATALOG (type -> {topic,version,schemaId}) + EventType union +
 *                   PayloadByType + TypedEnvelope/AnyEvent. The topic/version come from the
 *                   hand-maintained `topics.ts` registry's twin source — kept identical to
 *                   contracts/registry/event-backbone.index.json.
 *
 * IMPORTANT: this module COMPLEMENTS the hand-maintained `topics.ts` (which is the runtime
 * registry the package uses). The generated catalog adds the *typed payload* layer on top.
 * json-schema-to-typescript names interfaces from each schema's `title`; we map event_type ->
 * that generated name deterministically (same transform as the lib's pascal()).
 *
 * Generated files are committed so `pnpm typecheck` needs no codegen step; regenerate on any
 * schema change (paired with a version bump + `contracts:snapshot`).
 */

import { mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { compile } from 'json-schema-to-typescript';
import { buildIndex, SCHEMAS_DIR, REPO_ROOT } from './lib.mjs';

const OUT_DIR = join(REPO_ROOT, 'packages', 'events', 'src', 'generated');

const HEADER =
  '/* AUTO-GENERATED by tools/codegen/generate-types.mjs from contracts/schemas/. DO NOT EDIT.\n' +
  ' * Regenerate: `pnpm codegen:types`. Source of truth = the JSON Schemas (P1). */\n\n';

/** json-schema-to-typescript names an interface after the schema `title` (PascalCased). */
function nameFromTitle(title) {
  return title
    .split(/[.\-_ ]/)
    .filter(Boolean)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
}

/**
 * Compile ALL schemas in one pass via a synthetic root whose `properties` $ref every schema.
 * json-schema-to-typescript then emits each referenced interface ONCE (shared sub-schemas like
 * Explanation / CreativeDNA are de-duplicated), avoiding redeclaration errors.
 */
async function generatePayloads(index) {
  const root = {
    $id: 'https://contracts.growth-os.dev/schemas/_generated-root.schema.json',
    title: 'GeneratedRoot',
    type: 'object',
    additionalProperties: false,
    properties: {},
  };
  // reference every non-envelope schema by $ref so its types are pulled in + named by title
  for (const s of index.schemas) {
    if (s.kind === 'envelope') continue;
    root.properties[s.name] = { $ref: `${s.name}.schema.json` };
  }

  const ts = await compile(root, 'GeneratedRoot', {
    bannerComment: '',
    additionalProperties: false,
    declareExternallyReferenced: true,
    unreachableDefinitions: true,
    cwd: SCHEMAS_DIR,
  });

  // drop the synthetic GeneratedRoot interface itself (keep only the real payload/artifact types)
  const cleaned = ts.replace(/export interface GeneratedRoot \{[\s\S]*?\n\}\n/, '').trim();
  writeFileSync(join(OUT_DIR, 'payloads.ts'), HEADER + cleaned + '\n', 'utf8');

  // map event_type -> the generated interface name (from the schema title)
  const typeToName = new Map();
  for (const s of index.schemas) {
    if (s.kind !== 'event' || !s.event_type) continue;
    const schema = JSON.parse(readFileSync(join(SCHEMAS_DIR, s.name + '.schema.json'), 'utf8'));
    typeToName.set(s.event_type, nameFromTitle(schema.title ?? s.name));
  }
  return typeToName;
}

function generateCatalog(index, typeToName) {
  const events = index.schemas.filter((s) => s.kind === 'event' && s.event_type);
  const names = [...new Set(events.map((e) => typeToName.get(e.event_type)))];

  const lines = [HEADER];
  lines.push(`import type {\n  ${names.join(',\n  ')},\n} from './payloads.js';\n`);
  lines.push("import type { EventEnvelope } from '../envelope.js';\n\n");

  lines.push('/** Every canonical event type on the bus (§6.2 catalog). */\n');
  lines.push('export type EventType =\n');
  lines.push(events.map((e) => `  | '${e.event_type}'`).join('\n') + ';\n\n');

  lines.push('export interface EventMeta {\n');
  lines.push('  readonly type: EventType;\n  readonly topic: string;\n  readonly version: string;\n  readonly schemaId: string;\n}\n\n');
  lines.push('/** type -> { topic, version, schemaId }. Mirrors contracts/registry/event-backbone.index.json. */\n');
  lines.push('export const EVENT_CATALOG = {\n');
  for (const e of events) {
    lines.push(
      `  '${e.event_type}': { type: '${e.event_type}', topic: '${e.topic}', version: '${e.version}', schemaId: '${e.$id}' },\n`,
    );
  }
  lines.push('} as const satisfies Record<EventType, EventMeta>;\n\n');

  lines.push('/** type -> its payload interface (typed payload layer over topics.ts). */\n');
  lines.push('export interface PayloadByType {\n');
  for (const e of events) lines.push(`  '${e.event_type}': ${typeToName.get(e.event_type)};\n`);
  lines.push('}\n\n');

  lines.push('/** Fully-typed envelope for a given event type. */\n');
  lines.push('export type TypedEnvelope<T extends EventType> = EventEnvelope<PayloadByType[T]> & { type: T };\n\n');
  lines.push('/** Discriminated union of every typed envelope (consumer switch exhaustiveness). */\n');
  lines.push('export type AnyEvent =\n');
  lines.push(events.map((e) => `  | TypedEnvelope<'${e.event_type}'>`).join('\n') + ';\n\n');

  lines.push('export const ALL_EVENT_TYPES: readonly EventType[] = Object.keys(EVENT_CATALOG) as EventType[];\n');

  writeFileSync(join(OUT_DIR, 'catalog.ts'), lines.join(''), 'utf8');
}

async function main() {
  mkdirSync(OUT_DIR, { recursive: true });
  const index = buildIndex();
  const typeToName = await generatePayloads(index);
  generateCatalog(index, typeToName);
  console.log(`[codegen] wrote payloads + catalog (${typeToName.size} event types) -> ${OUT_DIR}`);
}

main().catch((e) => {
  console.error('[codegen] FAILED:', e);
  process.exit(1);
});
