#!/usr/bin/env node
/**
 * Generate the TypeScript SDK type surface from the OpenAPI 3.1 contracts (BUILD-SPEC P1,
 * §17.5 "everything the dashboard can do, the API can do"). Output -> packages/sdk/src/generated/.
 *
 *   node tools/codegen/generate-sdk.mjs
 *
 * For each contracts/openapi/<surface>.yaml we emit an openapi-typescript `paths`+`components`
 * type module (no runtime). packages/sdk then wraps these with a tiny typed fetch client
 * (src/client.ts, hand-written, stable). Generated files are COMMITTED; CI re-runs codegen and
 * the drift gate fails if a committed generated file diverges from a fresh run.
 *
 * openapi-typescript's programmatic API is ESM dynamic-imported so this tool stays dependency-light
 * and degrades to a clear message if the dep isn't installed yet (pre-`pnpm install`).
 */

import { mkdirSync, readdirSync, writeFileSync, existsSync, rmSync } from 'node:fs';
import { join, basename } from 'node:path';
import { pathToFileURL } from 'node:url';
import { REPO_ROOT } from './lib.mjs';

const OPENAPI_DIR = join(REPO_ROOT, 'contracts', 'openapi');
const OUT_DIR = join(REPO_ROOT, 'packages', 'sdk', 'src', 'generated');

function listOpenapiSurfaces() {
  return readdirSync(OPENAPI_DIR)
    .filter((f) => f.endsWith('.yaml') && !f.startsWith('_'))
    .sort();
}

/** gateway.yaml -> gateway ; integration-hub.yaml -> integration-hub */
function surfaceName(file) {
  return basename(file, '.yaml');
}

async function loadOpenapiTs() {
  try {
    const mod = await import('openapi-typescript');
    return mod.default ?? mod;
  } catch (e) {
    console.error(
      '[sdk] openapi-typescript not installed yet. Run `pnpm install` first.\n' +
        '      (' + (e?.message ?? e) + ')',
    );
    process.exit(1);
  }
}

async function run() {
  if (existsSync(OUT_DIR)) rmSync(OUT_DIR, { recursive: true, force: true });
  mkdirSync(OUT_DIR, { recursive: true });

  const openapiTS = await loadOpenapiTs();
  const surfaces = listOpenapiSurfaces();
  const indexLines = [
    '// AUTO-GENERATED by tools/codegen/generate-sdk.mjs from contracts/openapi/. DO NOT EDIT.',
    '// One typed module per API surface. Re-run `pnpm codegen:sdk`. Source of truth = OpenAPI (P1).',
    '',
  ];

  for (const file of surfaces) {
    const name = surfaceName(file);
    const specUrl = pathToFileURL(join(OPENAPI_DIR, file));
    // openapi-typescript v7 returns an AST; astToString renders it.
    const ast = await openapiTS(specUrl, { alphabetize: true });
    const { astToString } = await import('openapi-typescript');
    const dts =
      `/* AUTO-GENERATED from contracts/openapi/${file} — DO NOT EDIT. Run \`pnpm codegen:sdk\`. */\n\n` +
      astToString(ast);
    const outFile = name + '.ts';
    writeFileSync(join(OUT_DIR, outFile), dts, 'utf8');
    // re-export under a namespace so `paths`/`components` from different surfaces don't collide.
    const ns = name.replace(/[-.]/g, '_');
    indexLines.push(`export * as ${ns} from './${name}.js';`);
  }

  writeFileSync(join(OUT_DIR, 'index.ts'), indexLines.join('\n') + '\n', 'utf8');
  console.log(`[sdk] ✓ generated ${surfaces.length} OpenAPI type modules -> packages/sdk/src/generated/`);
}

run().catch((e) => {
  console.error('[sdk] ❌', e?.message ?? e);
  process.exit(1);
});
